name: "OSSF Scorecard"
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0' # Run weekly
jobs:
  scorecard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run Scorecard
        uses: ossf/scorecard-action@v2
        with:
          results_file: results.sarif
